server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: https://four458adminservice.onrender.com
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=3

        - id: job-search-service
          uri: https://four458jobsearchservice.onrender.com
          predicates:
            - Path=/api/v1/jobs/**
          filters:
            - StripPrefix=3

        - id: notification-service
          uri: https://four458notificationservice.onrender.com
          predicates:
            - Path=/api/v1/alerts/**
          filters:
            - StripPrefix=3

        - id: ai-agent-service
          uri: http://localhost:8000
          predicates:
            - Path=/agent
