server:
  port: ${PORT:8086}
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    reactor.netty.http.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: https://four458adminservice.onrender.com
          predicates:
            - Path=/api/v1/admin/jobs/**
        - id: job-search-service
          uri: https://four458jobsearchservice.onrender.com
          predicates:
            - Path=/api/v1/jobs/**
        - id: notification-service
          uri: https://four458notificationservice.onrender.com
          predicates:
            - Path=/api/v1/alerts/**
        - id: ai-agent-service
          uri: http://localhost:8000
          predicates:
            - Path=/agent

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always